BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ADD [isBlocked] BIT NOT NULL CONSTRAINT [User_isBlocked_df] DEFAULT 0,
[role] NVARCHAR(1000) NOT NULL CONSTRAINT [User_role_df] DEFAULT 'user';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
